#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
RULES_FILE="${REPO_DIR}/rules/agent-rules.md"
OUTPUT="${1:-promptfooconfig.yaml}"

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
  echo "Usage: export-promptfoo.sh [output_file]"
  echo
  echo "Generate a promptfoo evaluation config from save-token rules + benchmark prompts."
  echo "Default output: promptfooconfig.yaml"
  echo
  echo "Requires: npm install -g promptfoo"
  exit 0
fi

PROMPTS_DIR="${REPO_DIR}/benchmarks/prompts"
if [ ! -d "$PROMPTS_DIR" ]; then
  echo "[FAIL] No benchmark prompts at $PROMPTS_DIR" >&2; exit 1
fi

rules_escaped=$(python3 -c "
import json
with open('$RULES_FILE') as f:
    print(json.dumps(f.read()))
")

{
  cat <<'HEADER'
# Generated by save-token export-promptfoo.sh
# Run: promptfoo eval

description: "save-token A/B evaluation"

prompts:
  - id: baseline
    raw: "{{task}}"
  - id: save-token-full
    raw: |
HEADER

  python3 -c "
with open('$RULES_FILE') as f:
    for line in f:
        print('      ' + line.rstrip())
"
  echo "      ---"
  echo "      {{task}}"
  echo

  cat <<'PROVIDERS'
providers:
  - id: openai:gpt-4o
  - id: anthropic:claude-sonnet-4-20250514

PROVIDERS

  echo "tests:"

  for prompt_file in "$PROMPTS_DIR"/*.md; do
    [ -f "$prompt_file" ] || continue
    name=$(basename "$prompt_file" .md)
    task=$(python3 -c "
import json
with open('$prompt_file') as f:
    content = f.read().strip()
    lines = [l for l in content.split('\n') if not l.startswith('#')]
    print(json.dumps(' '.join(lines).strip()))
")
    cat <<TESTCASE
  - description: "$name"
    vars:
      task: $task
    assert:
      - type: python
        value: "len(output.split('\\\\n')) < 80"
      - type: llm-rubric
        value: "Response follows YAGNI principle and avoids unnecessary code"
TESTCASE
  done
} > "$OUTPUT"

echo "[OK] Generated $OUTPUT with $(grep -c 'description:' "$OUTPUT") test cases"
echo "[TIP] Run: promptfoo eval"
